version: '3'
services:
  api:
    build: .
    ports: 
      - "8080:80"
    environment:
      - Server=db
      - Database=ICode
      - UID=sa
      - PWD=leron@1605
      - Redis=redis
    restart: always
    depends_on:
      - db
      - redis
  db:
    image: mcr.microsoft.com/mssql/server
    ports: 
      - "11433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=leron@1605
    volumes:
      - ./db:/var/opt/mssql/data
    restart: always
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
