version: '3'
services:
  api:
    build:
      context: .
      dockerfile: ICode.API/Dockerfile
    environment:
      - DbConnectionString=Server=db;Database=ICode;UID=sa;PWD=leron@1605
      - HangFireDb=Server=db;Database=HangFire;UID=sa;PWD=leron@1605
      - Redis=redis,abortConnect=false
    restart: always
    depends_on:
      - db
      - redis
  web:
    build:
      context: .
      dockerfile: ICode.Web/Dockerfile
    environment:
      - ICode.API=http://api
      - Oauth__Google__RedirectURL=http://localhost:3000/auth/google/callback
    restart: always
    depends_on:
      - api
  db:
    build: 
      context: ./Services/database
      dockerfile: Dockerfile
    ports: 
      - "11433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=leron@1605
    volumes:
      - ./Services/database:/var/opt/mssql/data
    restart: always
  redis:
    image: redis:7.0.5-alpine
    ports:
      - "6379:6379"
  nginx:
    build:
      context: ./Services/nginx
    ports:
      - "3000:80"
    restart: always
