version: '3'
services:
  api:
    build: .
    ports: 
      - "8080:80"
    environment:
      - DbConnectionString=Server=db;Database=ICode;UID=sa;PWD=leron@1605
      - HangFireDb=Server=db;Database=HangFire;UID=sa;PWD=leron@1605
      - Redis="redis,abortConnect=false"
    restart: always
    depends_on:
      - db
      - redis
  db:
    build: 
      context: ./db
      dockerfile: Dockerfile
    ports: 
      - "11433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=leron@1605
    volumes:
      - ./db:/var/opt/mssql/data
    restart: always
  redis:
    image: redis:7.0.5-alpine
    ports:
      - "6379:6379"
