version: '3'
services:
  api:
    image: rubeha/icode_api
    environment:
      - ConnectionStrings__ICode=Server=db;Database=ICode;UID=sa;PWD=leron@1605
      - ConnectionStrings__Master=Server=db;UID=sa;PWD=leron@1605
      - ConnectionStrings__HangFire=Server=db;Database=HangFire;UID=sa;PWD=leron@1605
      - ConnectionStrings__Redis=redis,abortConnect=false
    depends_on:
      - db
      - redis
    restart: always
  web:
    image: rubeha/icode_web
    environment:
      - ICode.API=http://api
      - Oauth__Google__RedirectURL=http://icode1605.tech/auth/google/callback
    depends_on:
      - api
    restart: always
  code_executor:
    image: rubeha/code_executor
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=leron@1605
    volumes:
      - "/usr/src/icode/database:/var/opt/mssql/data"
    restart: always
  redis:
    image: redis:7.0.5-alpine
    ports:
      - "6379:6379"
  nginx:
    image: rubeha/icode_nginx
    ports:
      - "80:80"
    restart: always
    depends_on:
      - api
      - web
      - code_executor