version: '3'
services:
  api:
    image: rubeha/icode_api
    environment:
      - ConnectionStrings__ICode=Server=db;Database=ICode;UID=sa;PWD=leron@1605
      - ConnectionStrings__Master=Server=db;Database=master;UID=sa;PWD=leron@1605
      - ConnectionStrings__HangFire=Server=db;Database=HangFire;UID=sa;PWD=leron@1605
      - ConnectionStrings__Redis=redis,abortConnect=false
    restart: always
    depends_on:
      - db
      - redis
  web:
    image: rubeha/icode_web
    environment:
      - ICode.API=http://api
      - Oauth__Google__RedirectURL=http://icode-1605.tech/auth/google/callback
    restart: always
    depends_on:
      - api
  code_executor:
    image: rubeha/code_executor
    restart: always
  db:
    image: rubeha/icode_db
    ports: 
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=leron@1605
    volumes:
      - ./database:/var/opt/mssql/data
    restart: always
  redis:
    image: redis:7.0.5-alpine
    ports:
      - "6379:6379"
  nginx:
    image: rubeha/icode_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
